/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Health */
        get: operations["get_health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/phrases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Phrases */
        get: operations["list_phrases_phrases_get"];
        put?: never;
        /** Save Phrase */
        post: operations["save_phrase_phrases_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/phrases/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** List Matches */
        post: operations["list_matches_phrases_matches_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/phrases/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate Phrase */
        post: operations["validate_phrase_phrases_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ErrorDetail
         * @description Mirrors `platform.errors.error_envelope`'s inner `"error"` object --
         *     a SEPARATE pydantic model (not imported from `platform.errors`, which
         *     is framework-free by design), used only to describe the shape in the
         *     generated OpenAPI document (tasks.md 7b.2).
         */
        ErrorDetail: {
            /** Code */
            code: string;
            /** Details */
            details?: {
                [key: string]: unknown;
            } | null;
            /** Message */
            message: string;
        };
        /**
         * ErrorEnvelope
         * @description `{"error": {code, message, details?}}` -- design.md's error envelope.
         */
        ErrorEnvelope: {
            error: components["schemas"]["ErrorDetail"];
        };
        /**
         * ValidationStatus
         * @description Mirrors the `validation_status` CHECK constraint (migration 0001, the
         *     Alembic revision that creates the `phrases` table -- see design.md's
         *     "Data Model and Migrations").
         * @enum {string}
         */
        ValidationStatus: "unique" | "duplicate_confirmed";
        /** _MatchesData */
        _MatchesData: {
            /** Has More */
            has_more: boolean;
            /** Matches */
            matches: components["schemas"]["_ScoredPhrase"][];
            /** Next Cursor */
            next_cursor: string | null;
            /** Total */
            total: number;
        };
        /** _MatchesRequest */
        _MatchesRequest: {
            /**
             * Cursor
             * @description Opaque; clients MUST NOT parse it.
             */
            cursor: string;
            /** Limit */
            limit?: number | null;
            /** Text */
            text: string;
        };
        /** _MatchesResponse */
        _MatchesResponse: {
            data: components["schemas"]["_MatchesData"];
        };
        /** _PhraseListData */
        _PhraseListData: {
            /** Has More */
            has_more: boolean;
            /** Items */
            items: components["schemas"]["_PhraseOut"][];
            /** Next Cursor */
            next_cursor: string | null;
            /** Total */
            total: number;
        };
        /** _PhraseListResponse */
        _PhraseListResponse: {
            data: components["schemas"]["_PhraseListData"];
        };
        /**
         * _PhraseOut
         * @description The 201 body of `POST /phrases`.
         */
        _PhraseOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: string;
            /** Text */
            text: string;
            validation: components["schemas"]["_ValidationOut"];
        };
        /** _PhraseResponse */
        _PhraseResponse: {
            data: components["schemas"]["_PhraseOut"];
        };
        /** _SaveRequest */
        _SaveRequest: {
            /**
             * Confirm Duplicate
             * @default false
             */
            confirm_duplicate: boolean;
            /** Text */
            text: string;
        };
        /**
         * _ScoredPhrase
         * @description Shared shape of `most_similar` and each `matches[]` entry.
         */
        _ScoredPhrase: {
            /** Id */
            id: string;
            /** Score */
            score: number;
            /** Text */
            text: string;
        };
        /** _ValidateData */
        _ValidateData: {
            /** Has More */
            has_more: boolean;
            /** Is Duplicate */
            is_duplicate: boolean;
            /** Matches */
            matches: components["schemas"]["_ScoredPhrase"][];
            most_similar: components["schemas"]["_ScoredPhrase"] | null;
            /** Next Cursor */
            next_cursor: string | null;
            /** Score */
            score: number | null;
            /** Threshold */
            threshold: number;
            /** Total */
            total: number;
        };
        /** _ValidateRequest */
        _ValidateRequest: {
            /** Limit */
            limit?: number | null;
            /** Text */
            text: string;
        };
        /** _ValidateResponse */
        _ValidateResponse: {
            data: components["schemas"]["_ValidateData"];
        };
        /** _ValidationOut */
        _ValidationOut: {
            /** Most Similar Phrase Id */
            most_similar_phrase_id: string | null;
            /** Score */
            score: number | null;
            /** Status */
            status: string;
            /**
             * Validated At
             * Format: date-time
             */
            validated_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_phrases_phrases_get: {
        parameters: {
            query?: {
                limit?: number | null;
                cursor?: string | null;
                status?: components["schemas"]["ValidationStatus"] | null;
                q?: string | null;
                min_score?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["_PhraseListResponse"];
                };
            };
            /** @description Error envelope; `error.code` = `INVALID_CURSOR`. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Error envelope; `error.code` = `VALIDATION_ERROR`. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    save_phrase_phrases_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["_SaveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["_PhraseResponse"];
                };
            };
            /** @description Error envelope; `error.code` = `DUPLICATE_CONFIRMATION_REQUIRED`. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Error envelope; `error.code` = `VALIDATION_ERROR`. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Error envelope; `error.code` = `EMBEDDING_UNAVAILABLE`. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Error envelope; `error.code` = `EMBEDDING_TIMEOUT`. */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_matches_phrases_matches_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["_MatchesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["_MatchesResponse"];
                };
            };
            /** @description Error envelope; `error.code` = `INVALID_CURSOR`. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Error envelope; `error.code` = `VALIDATION_ERROR`. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Error envelope; `error.code` = `EMBEDDING_UNAVAILABLE`. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Error envelope; `error.code` = `EMBEDDING_TIMEOUT`. */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    validate_phrase_phrases_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["_ValidateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["_ValidateResponse"];
                };
            };
            /** @description Error envelope; `error.code` = `VALIDATION_ERROR`. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Error envelope; `error.code` = `EMBEDDING_UNAVAILABLE`. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Error envelope; `error.code` = `EMBEDDING_TIMEOUT`. */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
}
